apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  CAMERA_NAME: {{ .Values.config.CAMERA_NAME }}
  RTSP_IP: {{ .Values.config.RTSP_IP }}
  OUTPUT_IMAGE_FORMAT: "{{ .Values.config.OUTPUT_IMAGE_FORMAT }}"
  AWS_S3_HOST: {{ .Values.config.AWS_S3_HOST }}
  AWS_S3_ACCESS_KEY: {{ .Values.config.AWS_S3_ACCESS_KEY }}
  AWS_S3_SECRET_KEY: {{ .Values.config.AWS_S3_SECRET_KEY }}
  AWS_S3_BUCKET: {{ .Values.config.AWS_S3_BUCKET }}