replicaCount: 1

name: "minimal-ai"

image:
    repository: repo.greatbear.io/<your-tenant-id>/minimal-ai
    tag: 0.0.1
    pullPolicy: Always

imagePullSecrets:
  - name: gbear-harbor-pull

nameOverride: ""
fullnameOverride: "minimal-ai"

# Config parameters described in application metadata
# and their values will be put here by the GB-deployer
config:
  # The url of the RTSP stream
  RTSP_STREAM: ""
  # The host of the MQTT Broker
  MQTT_BROKER: ""
  # The topic for inferences
  MQTT_TOPIC: ""
