# Default values for rabbitmq-producer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
strategyType: Recreate

image:
  # The default value for the repository and tag will change when published
  # to different environments. This will happen WITHOUT a change of the chart
  # version. The only official source for the entire chart is github.
  repository: "repo.greatbear.io/<your-tenant-id>/rabbitmq-producer"
  pullPolicy: Always
  # Overrides the image tag will default to chart appVersion if not set.
  tag: "0.0.1"

imagePullSecrets:
  - name: gbear-harbor-pull

nameOverride: ""
fullnameOverride: ""

gbConfig:
  # Config parameters described in gbear/appmetadata.yaml
  # Their values will be injected here by the Great Bear deployer
  brokerName: ""
  brokerPort: 5672
  username: ""
  password: ""
  queue: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ports:
  http:
    port: 80
    protocol: TCP

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

siteId: ""
