apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: rtsp-device-stream
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: rtsp-device-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rtsp-device-stream
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rtsp-device-stream
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: gbear-harbor-pull
      containers:
        - args:
            - -re
            - -stream_loop
            - "-1"
            - -i
            - video.ts
            - -c
            - copy
            - -f
            - rtsp
            - {{ .Values.config.OUTPUT_RTSP }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: rtsp-device-stream
          resources: {}
      restartPolicy: Always
status: {}


