syncserver:
  fullnameOverride: "bear-echo-syncserver"
  service:
    port: 8010

  config:
    apiKey: ""
    gbSiteID: ""
    gbSiteName: ""
    controlServerURL: ""

  image:
    repository: repo.greatbear.io/cisco/great-bear-sync-server
    pullPolicy: Always
    tag: 2.3.0

  imagePullSecrets:
    - name: gbear-harbor-pull


# for bear-echo helm charts

fullnameOverride: ""
service:
  type: NodePort
  port: 11777
  
ports:
  http:
    port: 11777
    protocol: TCP
    nodePort: "{{ default 31777 (int .Values.config.ACCESS_PORT)}}"

config:
  requestPath: "/"
  defaultEchoText: "hi"
  # needs to be base64 encoded json. like `echo -n '{}' | base64`
  gbNodeIDs: "e30="
  appName: "bear-echo-runtime"
  ACCESS_PORT: ""

image:
  repository: repo.greatbear.io/<your-tenant-id>/bear-echo
  pullPolicy: Always
  tag: 0.0.4

imagePullSecrets:
  - name: gbear-harbor-pull
