{{- if eq .Values.config.MONITORING "on" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "app.fullname" . }}-prometheus-exporter
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - interval: 15s
      port: http
      path: /metrics
  jobLabel: {{ template "app.fullname" . }}-prometheus-exporter
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "app.selector" . | nindent 6 }}
{{- end }}