apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  RTSP_STREAM: |
    {{ .Values.config.RTSP_STREAM }}
  MQTT_BROKER: |
    {{ .Values.config.MQTT_BROKER }}
  MQTT_TOPIC: |
    {{ .Values.config.MQTT_TOPIC }}
